name: Pipeline CI DevOps

# Quando essa automação vai rodar?
on:
  push:
    branches: [ "main" ]

# O que ela vai fazer?
jobs:
  build-e-teste:
    # Cria uma máquina virtual Ubuntu gratuita no GitHub
    runs-on: ubuntu-latest

    # Passos da nossa automação
    steps:
    - name: 1. Pegar o código do repositório
      uses: actions/checkout@v4

    - name: 2. Testar a construção da imagem Docker
      run: docker build -t meu-site-devops .